<?php $temp = array (
  'id' => '1',
  'site_name' => '乐尚商城',
  'key_word' => '资讯,cms,php',
  'description' => 'aaaa',
  'auto_news_verify' => '0',
  'auto_pro_verify' => '0',
  'pub_news_score' => '50',
  'pub_pro_score' => '80',
  'score_money' => '100',
  'logo' => '20160410212227_616.png',
  'favicon' => '20160327221309_574.ico',
  'template' => 'orange',
  'home_page_num' => '10',
  'admin_page_num' => '10',
  'mod_appraise' => '2',
  'every_max_score' => '5000',
  'closed' => '0',
  'site_close_html' => '&lt;div class=&quot;closed_box&quot;&gt;&lt;div class=&quot;closed_body_top&quot;&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;closed_body&quot;&gt;&lt;div class=&quot;content&quot;&gt;网站已关闭&lt;br/&gt;请您稍后访问&lt;/div&gt;&lt;/div&gt;&lt;div class=&quot;closed_shadow&quot;&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;clear&quot;&gt;&amp;nbsp;&lt;/div&gt;&lt;/div&gt;',
);?>